export const buttonData = [
  { id: "sign1", data: "AC" },
  { id: "sign2", data: "+/-" },
  { id: "sign3", data: "%" },
  { id: "sign4", data: "/" },
  { id: "sign5", data: "7" },
  { id: "sign6", data: "8" },
  { id: "sign7", data: "9" },
  { id: "sign8", data: "X" },
  { id: "sign9", data: "4" },
  { id: "sign10", data: "5" },
  { id: "sign11", data: "6" },
  { id: "sign12", data: "-" },
  { id: "sign13", data: "1" },
  { id: "sign14", data: "2" },
  { id: "sign15", data: "3" },
  { id: "sign16", data: "+" },
  { id: "sign17", data: "0" },
  { id: "sign18", data: "." },
  { id: "sign19", data: "=" },
];
